### ISSUE TITLE
To set scheduled backups

### ISSUE THREAD

**Issue by rsoorajs** [wmutschl/timeshift-autosnap-apt#12]
Can you add an option like to set auto backup every "n" days.that will be very usefull. right now its only backing up if we call 'apt' related actions. if we can schedule autobackup using timeshift it will worth and save our time.

An example..if we lost some configs when we playing with server,and if we dont called an 'apt' method recently the last backup file will be far away. instead if you add an option for backing up "n" days, probably if we choosed every one day we can easily restore the latest backup file. hope you understand.

Thank you

#feature

**Comment by daPhipz** [comment]
You can use the program `timeshift` for this - here is a link to a tutorial on how to do this: https://itsfoss.com/backup-restore-linux-timeshift/
