### ISSUE TITLE
Stop autosnap if no packages are upgraded

### ISSUE THREAD

**Issue by ajgringo619** [wmutschl/timeshift-autosnap-apt#4]
Is it possible to abort a snapshot if there's no packages to be upgraded/installed? I manually run my updates, usually on a daily basis. Many times there are no updates, but the autosnap is still being generated:
```
$ sudo aptitude safe-upgrade
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
Rsyncing /boot into the filesystem before the call to timeshift.
Rsyncing /boot/efi into the filesystem before the call to timeshift.
Using system disk as snapshot device for creating snapshots in BTRFS mode
Mounted '/dev/sdb4' at '/mnt/timeshift/backup'
Creating new backup...(BTRFS)
Saving to device: /dev/sdb4, mounted at path: /mnt/timeshift/backup
Created directory: /mnt/timeshift/backup/timeshift-btrfs/snapshots/2020-09-13_16-52-40
Created subvolume snapshot: /mnt/timeshift/backup/timeshift-btrfs/snapshots/2020-09-13_16-52-40/@
Created control file: /mnt/timeshift/backup/timeshift-btrfs/snapshots/2020-09-13_16-52-40/info.json
BTRFS Snapshot saved successfully (0s)
Tagged snapshot '2020-09-13_16-52-40': ondemand
```

**Comment by wmutschl** [comment]
This should not happen. I guess this is due to the fact that you are using `aptitude` instead of `apt` or `apt-get`. I have no experience with aptitude but it seems like it triggers the hook in every case. If you are using `apt` this won't happen. Does this solve your issue?

**Comment by ajgringo619** [comment]
Since there's no apt equivalent to **aptitude safe-upgrade**, I guess I'm stuck for now.

**Comment by wmutschl** [comment]
Ig I may ask: What does the aptitude safe-upgrade command do compared to apt upgrade? Do you know if aptitude supports its own hooks? If so, then you should add 
DPkg::Pre-Invoke {"/usr/bin/timeshift-autosnap-apt"; };
to the aptitude hooks rather than apt.
Unfortunately, I do not have any experience with aptitude, but maybe someone else can provide a solution for you? Timeshift is quite well supported on the linux mint forums btw.

**Comment by wmutschl** [comment]
Or try to changing the hook to DPkg::Pre-Install-Pkgs in 80-timeshift-autosnap-apt (see the makefile where this file is copied to)

**Comment by ajgringo619** [comment]
Looks like **aptitude safe-upgrade** isn't really any different than **apt upgrade**, at least on my Mint system. I'll have to test this on my VMs, but for now I will close this. I did try both of your suggestions; ended up getting (2) snapshots instead of 1!
